#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="loki"
prepare_service defaults single

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting loki ${LOKI_VERSION}"
exec loki -config.file ${CONFIG_PATH}/${CONFIG_FILE}
